name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Build App
      run: xcodebuild clean build -project CombineProject.xcodeproj -scheme CombineProject -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
